# Generated by Django 2.0.6 on 2018-07-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('tour_summary', models.CharField(max_length=100)),
                ('gender', models.CharField(default='m or f', max_length=6)),
                ('cost', models.CharField(default='$$$', max_length=8)),
                ('guests', models.CharField(default='1', max_length=2)),
                ('image', models.CharField(default='english', max_length=150)),
            ],
        ),
    ]
