# Generated by Django 2.0.6 on 2018-07-07 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tour_summary', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guests', models.IntegerField()),
                ('image', models.CharField(default='english', max_length=150)),
                ('category', models.CharField(default='other category', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='tour_summary',
        ),
        migrations.AddField(
            model_name='tourguide',
            name='name',
            field=models.CharField(default='username', max_length=20),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TourGuide'),
        ),
    ]
