# Generated by Django 2.0.6 on 2018-07-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_tourguide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourguide',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
