# Generated by Django 2.0.6 on 2018-07-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180707_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='oneliner',
            field=models.CharField(default='no tour details', max_length=100),
        ),
    ]
