# Generated by Django 2.0.6 on 2018-07-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tourguide_oneliner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleTourGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aboutme', models.CharField(default='I am a tour guide', max_length=500)),
                ('name', models.CharField(default='username', max_length=20)),
                ('oneliner', models.CharField(default='no tour details', max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1)),
                ('title', models.CharField(max_length=30)),
                ('tour_summary', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guests', models.IntegerField()),
                ('image', models.CharField(default='english', max_length=150)),
                ('category', models.CharField(default='other category', max_length=30)),
                ('tour_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TourGuide')),
            ],
        ),
    ]
