# Generated by Django 2.0.6 on 2018-07-10 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_singletourguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletourguide',
            name='tour_guide',
        ),
        migrations.DeleteModel(
            name='SingleTourGuide',
        ),
    ]
