# Generated by Django 2.0.6 on 2018-07-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180710_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='aboutme',
            field=models.CharField(default='no about me', max_length=500),
        ),
    ]
