# Generated by Django 2.0.6 on 2018-07-12 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_tourguide_aboutme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_guide',
        ),
    ]
